name: usercanal_flutter
description: A high-performance Flutter SDK for UserCanal CDP platform with analytics events and structured logging using raw TCP and FlatBuffers.
version: 0.1.0+1
homepage: https://usercanal.com
repository: https://github.com/usercanal/sdk-flutter

environment:
  sdk: ^3.2.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  meta: ^1.11.0

  # FlatBuffers serialization - using flat_buffers package
  flat_buffers: ^23.5.26

  # For UUID generation
  uuid: ^4.2.1

  # For JSON handling
  collection: ^1.18.0

  # Path operations for local storage
  path_provider: ^2.1.2

  # Network connectivity detection
  connectivity_plus: ^5.0.2

  # Device information collection
  device_info_plus: ^10.1.0

  # Package info for app version details
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting and analysis
  flutter_lints: ^3.0.1

  # For testing
  test: ^1.24.9
  mockito: ^5.4.4
  build_runner: ^2.4.7

flutter:
  # This package is a plugin for Flutter apps targeting mobile platforms
  plugin:
    platforms:
      android:
        package: com.usercanal.flutter
        pluginClass: UserCanalFlutterPlugin
      ios:
        pluginClass: UserCanalFlutterPlugin

# Platform support
platforms:
  android:
  ios:
